### ISSUE TITLE
event error

### ISSUE THREAD

**Issue by xxyyzz2050** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#8]
$ npm run dev

> node-express-mongodb-jwt-rest-api-skeleton@1.2.7 dev D:\Downloads\__projects\N
odeJs\Angular\node-express-mongodb-jwt-rest-api-skeleton
> SET NODE_ENV=development & nodemon server.js

[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.
1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Emitted 'error' event at:
    at RedisClient.on_error (D:\Downloads\__projects\NodeJs\Angular\node-express
-mongodb-jwt-rest-api-skeleton\node_modules\redis\index.js:401:14)
    at Socket.<anonymous> (D:\Downloads\__projects\NodeJs\Angular\node-express-m
ongodb-jwt-rest-api-skeleton\node_modules\redis\index.js:279:14)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by davellanedam** [comment]
You should install redis 5+ to be able to run the project. Please remember to set connection values in .env file.
